sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234567hjkw

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t97GpJoGNRADD9e45kV
    access-key-secret: oEC7Id5KlItacI3ciqiJOheybzHJJW
    bucket-name: mirage123

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10